test: retry integration tests on CI
We often have errors when downloading repodata.
Since these errors tend to not occur when retrying, the hope is that a simple automatic retry will help with our flaky tests.

Example of such an error:

```
FAILED tests/integration_python/test_main_cli.py::test_upgrade_pypi_and_conda_package - AssertionError: Return code was 1, expected 0, stderr: ERROR get_or_create_subdir{platform=NoArch channel=https://prefix.dev/conda-forge/}: error=error sending request for url (https://prefix.dev/conda-forge/noarch/repodata_shards.msgpack.zst)
error sending request for url (https://prefix.dev/conda-forge/noarch/repodata_shards.msgpack.zst)
    Diagnostic severity: error
    Caused by: client error (Connect)
    Caused by: An existing connection was forcibly closed by the remote host. (os error 10054)
```